// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlert = `-- name: CreateAlert :exec
INSERT INTO
alerts (incident_id, alert_email) 
VALUES ($1, $2)
`

type CreateAlertParams struct {
	IncidentID pgtype.UUID
	AlertEmail string
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) error {
	_, err := q.db.Exec(ctx, createAlert, arg.IncidentID, arg.AlertEmail)
	return err
}

const updateAlertStatus = `-- name: UpdateAlertStatus :execrows
UPDATE alerts
SET
    status = $2
WHERE id = $1
`

type UpdateAlertStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAlertStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
