// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID         pgtype.UUID
	IncidentID pgtype.UUID
	SentAt     pgtype.Timestamptz
	AlertEmail string
	Status     string
	CreatedAt  pgtype.Timestamptz
}

type Monitor struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Url                string
	AlertEmail         pgtype.Text
	IntervalSec        int32
	TimeoutSec         int32
	LatencyThresholdMs int32
	ExpectedStatus     int32
	Enabled            bool
	UpdatedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

type MonitorIncident struct {
	ID         pgtype.UUID
	MonitorID  pgtype.UUID
	StartTime  pgtype.Timestamptz
	EndTime    pgtype.Timestamptz
	Alerted    bool
	HttpStatus int32
	LatencyMs  int32
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Name          string
	Email         string
	PasswordHash  string
	MonitorsCount pgtype.Int4
	IsPaidUser    pgtype.Bool
	CreatedAt     pgtype.Timestamptz
}
