// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: monitor_incidents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeMonitorIncident = `-- name: CloseMonitorIncident :execrows
UPDATE monitor_incidents
SET end_time = $2
WHERE monitor_id = $1 AND end_time IS NULL
`

type CloseMonitorIncidentParams struct {
	MonitorID pgtype.UUID
	EndTime   pgtype.Timestamptz
}

func (q *Queries) CloseMonitorIncident(ctx context.Context, arg CloseMonitorIncidentParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeMonitorIncident, arg.MonitorID, arg.EndTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createMonitorIncident = `-- name: CreateMonitorIncident :exec
INSERT INTO monitor_incidents (monitor_id, start_time, alerted, http_status, latency_ms)
VALUES ($1, $2, $3, $4, $5)
`

type CreateMonitorIncidentParams struct {
	MonitorID  pgtype.UUID
	StartTime  pgtype.Timestamptz
	Alerted    bool
	HttpStatus int32
	LatencyMs  int32
}

func (q *Queries) CreateMonitorIncident(ctx context.Context, arg CreateMonitorIncidentParams) error {
	_, err := q.db.Exec(ctx, createMonitorIncident,
		arg.MonitorID,
		arg.StartTime,
		arg.Alerted,
		arg.HttpStatus,
		arg.LatencyMs,
	)
	return err
}

const getMonitorIncidentByID = `-- name: GetMonitorIncidentByID :one
SELECT id, monitor_id, start_time, end_time, alerted, http_status, latency_ms, created_at
FROM monitor_incidents
WHERE id = $1
`

func (q *Queries) GetMonitorIncidentByID(ctx context.Context, id pgtype.UUID) (MonitorIncident, error) {
	row := q.db.QueryRow(ctx, getMonitorIncidentByID, id)
	var i MonitorIncident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartTime,
		&i.EndTime,
		&i.Alerted,
		&i.HttpStatus,
		&i.LatencyMs,
		&i.CreatedAt,
	)
	return i, err
}
